### PR TITLE
data:p10: Add ATTR_AVSBUS_BUSNUM and ATTR_AVSBUS_RAIL

### PR DESCRIPTION
**Pull request by aravynd**
New version of start_cbs would require these two new attributes
 to be present in the devtree

Signed-off-by: Aravind T Nair <aravynd@gmail.com>

### CODE REVIEW

**Review by ojayanth — CHANGES_REQUESTED** [review]
Better to split the commits into two's . This will help to revert the commit if required .
Also what is the persistency of this attribute?
Add verified section in the commits

**Comment by aravynd** [comment]
> 
Checked with Nick and the attributes are non volatile / readonly. So removed the preserved_attrs_list change.
Ramesh verified the changes.
I don't think we need to split this commit anymore.

**Comment by ojayanth** [comment]
Incase no attribute dependency , prefer to keep  individual attribute level  commits .  That is the common process pdata follows.

**Comment by aravynd** [comment]
> Incase no attribute dependency , prefer to keep individual attribute level commits . That is the common process pdata follows.

These two attributes are to be consumed by a new version of the start cbs and HB needs this soon enough. So I'm not quite sure they are unrelated and warrants two commits.

**Review by RameshIyyar — APPROVED** [review]
IMV, those 2 attributes are added for the same feature so I think it is ok to keep those 2 attributes in the same commit instead of a separate commit for each attribute.

**Pull request merged**
