### PR TITLE
scripts : Port MRW parser changes from hostboot

### PR DESCRIPTION
**Pull request by devenrao**
scripts : Port MRW parser changes from hostboot

Hostboot made changes to the MRW parser scripts to support new system type the same has been ported over to BMC for device tree generation.

- processMrw.pl
  hostboot/src/usr/targeting/common/processMrw.pl

- Targets.pm
  hostboot/src/usr/targeting/common/Targets.pm

- BusFruCallouts.pm
  hostboot/src/usr/targeting/common/BusFruCallouts.pm

Tested:
1) Everest used Everest-MRW.dtb device tree file and
ensured system reached runtime.

2) Raininer2U used Rainier-2U-MRW.dtb device tree
file and ensured system reached runtime.

3) Rainier4U used Rainier-4U-MRW.dtb device tree file and
ensured system reached runtime.

Change-Id: I853f53fcec35c499a39295dd34037f08c9867a95
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>

### CODE REVIEW

**Review by RameshIyyar — COMMENTED** [review]
Can you please follow the commit message template like this https://github.com/open-power/pdata/commit/91da7ab83d107dca383514a90cda9d0304360c0b ? it helps us a lot in the future. (I would like to include the last hostboot repo commit id of each file change)

Please include why are we porting this now like what was the issue or any new requirement

Note: if some term is confidential like system name, etc please ignore those terms in the commit message (and code if possible).

Please include test case details like those added in the above commit template since the device tree changes affect IPLing so we need to make sure that all system are reached runtime and is able to guard all targets (since hardware numbering or topology changes may happen in the HB scripts).

**Comment by ojayanth** [comment]
Looks like major change. What is driving this changes now.?

**Comment by devenrao** [comment]
> Looks like major change. What is driving this changes now.?

new target

**Comment by devenrao** [comment]
will wait for hostboot to merge the script changes before merging these changes.

**Review by RameshIyyar — APPROVED** [review]

**Review by aravynd — APPROVED** [review]

**Pull request merged**
